### ISSUE TITLE
rdf2marc raising Work (bf:instanceOf) ... (Rdf2marc::BadRequestError) on all requests

### ISSUE THREAD

**Issue by aaron-collier** [LD4P/rdf2marc#104]
When I run the rdf2marc command line tool against a URI from the application:

```
exe/rdf2marc https://api.development.sinopia.io/resource/f10f6421-8a6a-4705-bc6a-6d5052f34bc5
```

I get:

```
Traceback (most recent call last):
	2: from exe/rdf2marc:16:in `<main>'
	1: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/converter.rb:8:in `convert'
/Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/graphs_loader.rb:11:in `from_instance_uri': Work (bf:instanceOf) not specified for Instance (Rdf2marc::BadRequestError)`
```

**Comment by aaron-collier** [comment]
Perhaps this should go in it's own ticket, but capturing here for now:

Trying a different resource per @michelleif suggestion:

```
exe/rdf2marc https://api.development.sinopia.io/resource/4bf07817-38a4-41d5-8498-8a9a36b88ec4
```

Results in a different error:
```
Traceback (most recent call last):
	11: from exe/rdf2marc:16:in `<main>'
	10: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/converter.rb:13:in `convert'
	 9: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model.rb:9:in `to_model'
	 8: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mapper.rb:19:in `generate'
	 7: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb:11:in `generate'
	 6: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb:24:in `publication_distributions'
	 5: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb:37:in `publication_distributions_for'
	 4: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb:37:in `map'
	 3: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb:41:in `block in publication_distributions_for'
	 2: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb:55:in `publication_distributions_names'
	 1: from /Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb:55:in `map'
/Users/amcollie/github/LD4P/rdf2marc/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb:56:in `block in publication_distributions_names': undefined method `value' for #<RDF::Node:0x2800(_:b42)> (NoMethodError)
Did you mean?  evaluate
```

**Comment by justinlittman** [comment]
@NancyL `ld4p:RT:bf2:Provision:Name` has a property `http://id.loc.gov/ontologies/bibframe/Agent`. Should this be ``http://id.loc.gov/ontologies/bibframe/agent`?

![image](https://user-images.githubusercontent.com/588335/134186867-82ff6046-eb11-45d1-ad68-3ad347d5ba1a.png)

**Comment by justinlittman** [comment]
Actually, that whole template seems odd. `ld4p:RT:bf2:Provision:Name` has the class BF:Agent, but it has an agent property.

**Comment by NancyL** [comment]
please look at the pcc:bf2:Provision:Name. Yes, the ld4p one is a mess, as was the pcc one. I have fixed the pcc one. I will fix the ld4p one some time today. But let's concentrate on the pcc templates for now

**Comment by aaron-collier** [comment]
I am still getting errors, and don't really understand any of the above discussion, so that's up to you all, but I'm blocked on using rdf2marc.

**Comment by aaron-collier** [comment]
@jermnelson was able to walk me through finding valid objects, so if this is expected behavior as I saw above, feel free to close.
